apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-flight-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   
  hostPath:
    path: /mnt/data/mongo-flight-db
