apiVersion: v1
kind: PersistentVolume
metadata:
  name: flight-db-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /mnt/data/flight-db
